//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileProtectionUtility {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileProtectionUtility.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Utilità di protezione file.
        /// </summary>
        public static string ConsoleTitle {
            get {
                return ResourceManager.GetString("ConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Decodifica in corso....
        /// </summary>
        public static string DecryptingString {
            get {
                return ResourceManager.GetString("DecryptingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operazione completata, ma il file originale non è stato eliminato..
        /// </summary>
        public static string DeletionFailedWarningMessageString {
            get {
                return ResourceManager.GetString("DeletionFailedWarningMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codifica in corso....
        /// </summary>
        public static string EncryptingString {
            get {
                return ResourceManager.GetString("EncryptingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Premere un tasto per uscire....
        /// </summary>
        public static string ExitString {
            get {
                return ResourceManager.GetString("ExitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il file specificato non esiste..
        /// </summary>
        public static string FileNotFoundErrorString {
            get {
                return ResourceManager.GetString("FileNotFoundErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operazione non riuscita: .
        /// </summary>
        public static string GeneralErrorString {
            get {
                return ResourceManager.GetString("GeneralErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserire password: .
        /// </summary>
        public static string InsertPasswordString {
            get {
                return ResourceManager.GetString("InsertPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Estensione non valida..
        /// </summary>
        public static string InvalidExtensionErrorString {
            get {
                return ResourceManager.GetString("InvalidExtensionErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operazione completata, ma uno o più dei file originali non sono stati eliminati..
        /// </summary>
        public static string MultipleDeletionFailedWarningMessageString {
            get {
                return ResourceManager.GetString("MultipleDeletionFailedWarningMessageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Una o più operazioni non riuscite..
        /// </summary>
        public static string MultipleOperationFailedErrorString {
            get {
                return ResourceManager.GetString("MultipleOperationFailedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non è stata digita alcuna password, operazione annullata..
        /// </summary>
        public static string NoPasswordProvidedErrorString {
            get {
                return ResourceManager.GetString("NoPasswordProvidedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operazione completata..
        /// </summary>
        public static string OperationCompletedString {
            get {
                return ResourceManager.GetString("OperationCompletedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operazione non riuscita..
        /// </summary>
        public static string OperationFailedErrorString {
            get {
                return ResourceManager.GetString("OperationFailedErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Uso:
        ///
        ///FileEncryptionUtility /{comando} {percorso} {password} [-opzioni]
        ///
        ///Comandi:
        ///
        ////encrypt: esegue la cifratura di un file
        ////decrypt: esegue la decodifica di un file
        ///
        ///Opzioni:
        ///
        ///-overwrite: sovrascrive il file se esiste già
        ///-recurse: esegue il comando su tutti i file nella directory e nelle sottodirectory
        ///-keeporiginal: mantiene il file originale
        ///
        ///Il percorso del file può essere assoluto o relativo.
        ///L&apos;opzione -recurse non ha effetto se il percorso non punta a una directory.
        ///Se il percorso pu [stringa troncata]&quot;;.
        /// </summary>
        public static string ParametersString {
            get {
                return ResourceManager.GetString("ParametersString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Comando non riconosciuto..
        /// </summary>
        public static string UnrecognizedCommandErrorString {
            get {
                return ResourceManager.GetString("UnrecognizedCommandErrorString", resourceCulture);
            }
        }
    }
}
